# Generated by Django 4.1.1 on 2022-10-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploadimgapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="picture",
            field=models.ImageField(blank=True, upload_to="my_picture"),
        ),
    ]
