# Generated by Django 4.1.1 on 2022-10-03 08:45

from django.db import migrations, models
import uploadimgapp.models


class Migration(migrations.Migration):

    dependencies = [
        ("uploadimgapp", "0002_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="picture",
            field=models.ImageField(
                blank=True, upload_to=uploadimgapp.models.profile.namefile
            ),
        ),
    ]
